### ISSUE TITLE
Update Infrastructure

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#851]
[Server Infrastructure](../wiki/Infrastructure) needs updates
- [x] #831 update PHP
- [x] #554 upgrade Nexus Repository Manager
- [x] #515 replace the blog module and enable spam filter #559 
- [x] upgrade JDK (was done in #553)
- [x] #956. #553 upgrade Jenkins CI
- [x] support for SSL/HTTPS 
- [x] #636 add A record for ```deegree.org``` to DNS entry
see also #675 about the last changes to the server.

Get in concat with FOSSGIS eV and [OSGeo sysadmin list](https://lists.osgeo.org/mailman/listinfo/sac) about the domain and administration of the server, see [FOSSGIS Wiki](https://www.fossgis.de/wiki/IT-Technik).

**Comment by copierrj** [comment]
Regarding the upgrade of Nexus:

It is no longer possible to download Nexus as a war file. We should however be able to install the provided 'bundle' (jetty + nexus).

Current configuration is in /usr/local/tomcat/nexus/webapps/ROOT/WEB-INF/plexus.properties
New configuration: ${install_dir}/conf/nexus.properties

**Comment by stephanr** [comment]
For the htts/ssl stuff, we talked about using a small footprint implementaion of lets-encrypt ACME protocol (https://github.com/lukas2511/dehydrated).
After the server upgrade has been completed i will work on implementing https for plaza.deegree.org.

**Comment by copierrj** [comment]
Individual sysadmin actions:

- dist upgrade to debian 8
- apache
  - upgrade config to 2.4
  - switch from mod_jk to mod_proxy
  - add https support
  - test all configured sites
- apt-get openjdk-8
- tomcat
  - manually upgrade to 8.5 (unzip dist to /usr/local)
  - configure init.d scripts
  - test all instances
- nexus
  - install using bundle
  - create init.d script
  - remove obsolete tomcat instance
- jenkins
  - replace war file
- website
  - update joomla
  - install new blog module
  - enable spam filter

**Comment by tfr42** [comment]
- [ ] Upgrade postgresql from 9.1 to 9.4 required. postgres is used by ogcri.deegree.org services.

**Comment by stephanr** [comment]
Post-Installation Steps:
  * [ ] Archive the old wiki completely
    * [ ] create a html dump from the pages
    * [ ] setup apache to server static archive files
    * [ ] remove the old software moinmoinwiki / configuration / maybe database content

**Comment by stephanr** [comment]
@tfr42 moinmoin wiki has been reactivated by disabling some manual tweaks and disabling the creation of new users.

Creating a html-only dump is from my point of view a desirable task (as the software was manually tweaked before on the user-handling and maybe this got lost on upgrade)

**Comment by stephanr** [comment]
The SSL support has been enabled and configured in apache2 based on letsencyrpt certificates.
Expirering notifications will be sent to the tmc mailing list, dehydrated was configured as systemd unit/timer to renew the certificates every two week.
The apache configuration will be reloaded automatically afterwards if the configuration has no syntax errors/problems.

I also adjusted accordingly the todo in comment above.

**Comment by tfr42** [comment]
to enable SSL see https://www.joomlart.com/tutorials/joomla-tutorials/how-to-use-ssl-in-a-joomla-site

**Comment by tfr42** [comment]
SSL support is working now for https://www.deegree.org/ some improvements for SEF are required.

**Comment by tfr42** [comment]
Next installation session planned for 2018 to update PHP (#831), Joomla!  and Nexus.

**Comment by stephanr** [comment]
In today's TMC meeting we decided that it is sufficient to keep the old wiki as read-only dump for archive purposes.
I will try to create a dump before the next Update/TMC Meeting.

**Comment by dstenger** [comment]
I also installed ```Oracle JDK 8``` on the server as otherwise the reference implementations do not pass any more (see #900 and #905). Just the Tomcat run by user ogcri is configured to use this Java installation.

If you have any questions, please feel free to contact me.

**Comment by tfr42** [comment]
> An Dump has been created and linked to http://apidoc.deegree.org/wiki-archive/ for preview purpose, after a further check the progress will conitnue later.

The static HTML pages of the old wiki look good for me. May be we replace the header images with stronger message that this is an archive version of the old wiki.

**Comment by stephanr** [comment]
The wiki has been replaced by a static dump and the software (pkg python-moinmoin) was deinstalled.
Also the logo has been altered to "-archived- deegree -wiki-" to state that this an read-only archive.

**Comment by stephanr** [comment]
For reference: Ticket to test if a migration of joomla is possible: https://github.com/deegree/deegree3/issues/906

**Comment by tfr42** [comment]
Upgrade to OpenJDK 1.8.0_201-b09 done

**Comment by tfr42** [comment]
Docker version 18.06.2-ce, build 6d37f41 installed on plaza. Currently disabled in systemctl!

**Comment by tfr42** [comment]
All services have been updated during server migration, see issue #1130.
